### PR TITLE
Configure Atlantis

### PR DESCRIPTION
**Pull request by drts01**
https://www.runatlantis.io/docs/atlantis-yaml-reference.html

### CODE REVIEW

**Comment by drts01** [comment]
**Plan Error**
```
atlantis.yaml files not allowed because Atlantis is not running with --allow-repo-config
```

**Comment by drts01** [comment]
atlantis apply

**Comment by drts01** [comment]
Ran Apply in dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by drts01** [comment]
atlantis plan

**Comment by drts01** [comment]
Ran Plan in dir: `.` workspace: `default`

```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_availability_zones.all: Refreshing state...
data.aws_ami.ubuntu: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_autoscaling_group.example
      id:                                     <computed>
      arn:                                    <computed>
      availability_zones.#:                   "2"
      availability_zones.1978419061:          "ca-central-1b"
      availability_zones.3974436559:          "ca-central-1a"
      default_cooldown:                       <computed>
      desired_capacity:                       <computed>
      force_delete:                           "false"
      health_check_grace_period:              "300"
      health_check_type:                      "ELB"
      launch_configuration:                   "${aws_launch_configuration.example.id}"
      load_balancers.#:                       "1"
      load_balancers.3603464733:              "terraform-asg-example"
      max_size:                               "3"
      metrics_granularity:                    "1Minute"
      min_size:                               "2"
      name:                                   <computed>
      protect_from_scale_in:                  "false"
      service_linked_role_arn:                <computed>
      tag.#:                                  "1"
      tag.4170447404.key:                     "Name"
      tag.4170447404.propagate_at_launch:     "true"
      tag.4170447404.value:                   "terraform-asg-example"
      target_group_arns.#:                    <computed>
      vpc_zone_identifier.#:                  <computed>
      wait_for_capacity_timeout:              "10m"

  + aws_elb.example
      id:                                     <computed>
      arn:                                    <computed>
      availability_zones.#:                   "2"
      availability_zones.1978419061:          "ca-central-1b"
      availability_zones.3974436559:          "ca-central-1a"
      connection_draining:                    "false"
      connection_draining_timeout:            "300"
      cross_zone_load_balancing:              "true"
      dns_name:                               <computed>
      health_check.#:                         "1"
      health_check.0.healthy_threshold:       "2"
      health_check.0.interval:                "30"
      health_check.0.target:                  "HTTP:8080/"
      health_check.0.timeout:                 "3"
      health_check.0.unhealthy_threshold:     "2"
      idle_timeout:                           "60"
      instances.#:                            <computed>
      internal:                               <computed>
      listener.#:                             "1"
      listener.3931999347.instance_port:      "8080"
      listener.3931999347.instance_protocol:  "http"
      listener.3931999347.lb_port:            "80"
      listener.3931999347.lb_protocol:        "http"
      listener.3931999347.ssl_certificate_id: ""
      name:                                   "terraform-asg-example"
      security_groups.#:                      <computed>
      source_security_group:                  <computed>
      source_security_group_id:               <computed>
      subnets.#:                              <computed>
      zone_id:                                <computed>

  + aws_launch_configuration.example
      id:                                     <computed>
      associate_public_ip_address:            "false"
      ebs_block_device.#:                     <computed>
      ebs_optimized:                          <computed>
      enable_monitoring:                      "true"
      image_id:                               "ami-db9e1cbf"
      instance_type:                          "t2.micro"
      key_name:                               <computed>
      name:                                   <computed>
      root_block_device.#:                    <computed>
      security_groups.#:                      <computed>
      user_data:                              "4430fd6498339061effa6d27ccf341a1e94569d7"

  + aws_security_group.elb
      id:                                     <computed>
      arn:                                    <computed>
      description:                            "Managed by Terraform"
      egress.#:                               "1"
      egress.482069346.cidr_blocks.#:         "1"
      egress.482069346.cidr_blocks.0:         "0.0.0.0/0"
      egress.482069346.description:           ""
      egress.482069346.from_port:             "0"
      egress.482069346.ipv6_cidr_blocks.#:    "0"
      egress.482069346.prefix_list_ids.#:     "0"
      egress.482069346.protocol:              "-1"
      egress.482069346.security_groups.#:     "0"
      egress.482069346.self:                  "false"
      egress.482069346.to_port:               "0"
      ingress.#:                              "1"
      ingress.2214680975.cidr_blocks.#:       "1"
      ingress.2214680975.cidr_blocks.0:       "0.0.0.0/0"
      ingress.2214680975.description:         ""
      ingress.2214680975.from_port:           "80"
      ingress.2214680975.ipv6_cidr_blocks.#:  "0"
      ingress.2214680975.protocol:            "tcp"
      ingress.2214680975.security_groups.#:   "0"
      ingress.2214680975.self:                "false"
      ingress.2214680975.to_port:             "80"
      name:                                   "terraform-example-elb"
      owner_id:                               <computed>
      revoke_rules_on_delete:                 "false"
      vpc_id:                                 <computed>

  + aws_security_group.example
      id:                                     <computed>
      arn:                                    <computed>
      description:                            "Managed by Terraform"
      egress.#:                               <computed>
      ingress.#:                              "1"
      ingress.516175195.cidr_blocks.#:        "1"
      ingress.516175195.cidr_blocks.0:        "0.0.0.0/0"
      ingress.516175195.description:          ""
      ingress.516175195.from_port:            "8080"
      ingress.516175195.ipv6_cidr_blocks.#:   "0"
      ingress.516175195.protocol:             "tcp"
      ingress.516175195.security_groups.#:    "0"
      ingress.516175195.self:                 "false"
      ingress.516175195.to_port:              "8080"
      name:                                   "terraform-example-instance"
      owner_id:                               <computed>
      revoke_rules_on_delete:                 "false"
      vpc_id:                                 <computed>
Plan: 5 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](https://13ce0140.ngrok.io/lock?id=CMeza99%252Fterraform-up-and-running%252F.%252Fdefault).

**Comment by drts01** [comment]
atlantis apply

**Comment by drts01** [comment]
Ran Apply in dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by CMeza99** [comment]
atlantis apply

**Comment by CMeza99** [comment]
Ran Apply in dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by drts01** [comment]
atlantis apply

**Comment by drts01** [comment]
Ran Apply in dir: `.` workspace: `default`

**Apply Error**
```
no plan found at path "." and workspace "default"–did you run plan?

```

**Comment by drts01** [comment]
atlantis plan

**Comment by drts01** [comment]
Ran Plan in dir: `.` workspace: `default`

```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_availability_zones.all: Refreshing state...
data.aws_ami.ubuntu: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_autoscaling_group.example
      id:                                     <computed>
      arn:                                    <computed>
      availability_zones.#:                   "2"
      availability_zones.1978419061:          "ca-central-1b"
      availability_zones.3974436559:          "ca-central-1a"
      default_cooldown:                       <computed>
      desired_capacity:                       <computed>
      force_delete:                           "false"
      health_check_grace_period:              "300"
      health_check_type:                      "ELB"
      launch_configuration:                   "${aws_launch_configuration.example.id}"
      load_balancers.#:                       "1"
      load_balancers.3603464733:              "terraform-asg-example"
      max_size:                               "3"
      metrics_granularity:                    "1Minute"
      min_size:                               "2"
      name:                                   <computed>
      protect_from_scale_in:                  "false"
      service_linked_role_arn:                <computed>
      tag.#:                                  "1"
      tag.4170447404.key:                     "Name"
      tag.4170447404.propagate_at_launch:     "true"
      tag.4170447404.value:                   "terraform-asg-example"
      target_group_arns.#:                    <computed>
      vpc_zone_identifier.#:                  <computed>
      wait_for_capacity_timeout:              "10m"

  + aws_elb.example
      id:                                     <computed>
      arn:                                    <computed>
      availability_zones.#:                   "2"
      availability_zones.1978419061:          "ca-central-1b"
      availability_zones.3974436559:          "ca-central-1a"
      connection_draining:                    "false"
      connection_draining_timeout:            "300"
      cross_zone_load_balancing:              "true"
      dns_name:                               <computed>
      health_check.#:                         "1"
      health_check.0.healthy_threshold:       "2"
      health_check.0.interval:                "30"
      health_check.0.target:                  "HTTP:8080/"
      health_check.0.timeout:                 "3"
      health_check.0.unhealthy_threshold:     "2"
      idle_timeout:                           "60"
      instances.#:                            <computed>
      internal:                               <computed>
      listener.#:                             "1"
      listener.3931999347.instance_port:      "8080"
      listener.3931999347.instance_protocol:  "http"
      listener.3931999347.lb_port:            "80"
      listener.3931999347.lb_protocol:        "http"
      listener.3931999347.ssl_certificate_id: ""
      name:                                   "terraform-asg-example"
      security_groups.#:                      <computed>
      source_security_group:                  <computed>
      source_security_group_id:               <computed>
      subnets.#:                              <computed>
      zone_id:                                <computed>

  + aws_launch_configuration.example
      id:                                     <computed>
      associate_public_ip_address:            "false"
      ebs_block_device.#:                     <computed>
      ebs_optimized:                          <computed>
      enable_monitoring:                      "true"
      image_id:                               "ami-db9e1cbf"
      instance_type:                          "t2.micro"
      key_name:                               <computed>
      name:                                   <computed>
      root_block_device.#:                    <computed>
      security_groups.#:                      <computed>
      user_data:                              "4430fd6498339061effa6d27ccf341a1e94569d7"

  + aws_security_group.elb
      id:                                     <computed>
      arn:                                    <computed>
      description:                            "Managed by Terraform"
      egress.#:                               "1"
      egress.482069346.cidr_blocks.#:         "1"
      egress.482069346.cidr_blocks.0:         "0.0.0.0/0"
      egress.482069346.description:           ""
      egress.482069346.from_port:             "0"
      egress.482069346.ipv6_cidr_blocks.#:    "0"
      egress.482069346.prefix_list_ids.#:     "0"
      egress.482069346.protocol:              "-1"
      egress.482069346.security_groups.#:     "0"
      egress.482069346.self:                  "false"
      egress.482069346.to_port:               "0"
      ingress.#:                              "1"
      ingress.2214680975.cidr_blocks.#:       "1"
      ingress.2214680975.cidr_blocks.0:       "0.0.0.0/0"
      ingress.2214680975.description:         ""
      ingress.2214680975.from_port:           "80"
      ingress.2214680975.ipv6_cidr_blocks.#:  "0"
      ingress.2214680975.protocol:            "tcp"
      ingress.2214680975.security_groups.#:   "0"
      ingress.2214680975.self:                "false"
      ingress.2214680975.to_port:             "80"
      name:                                   "terraform-example-elb"
      owner_id:                               <computed>
      revoke_rules_on_delete:                 "false"
      vpc_id:                                 <computed>

  + aws_security_group.example
      id:                                     <computed>
      arn:                                    <computed>
      description:                            "Managed by Terraform"
      egress.#:                               <computed>
      ingress.#:                              "1"
      ingress.516175195.cidr_blocks.#:        "1"
      ingress.516175195.cidr_blocks.0:        "0.0.0.0/0"
      ingress.516175195.description:          ""
      ingress.516175195.from_port:            "8080"
      ingress.516175195.ipv6_cidr_blocks.#:   "0"
      ingress.516175195.protocol:             "tcp"
      ingress.516175195.security_groups.#:    "0"
      ingress.516175195.self:                 "false"
      ingress.516175195.to_port:              "8080"
      name:                                   "terraform-example-instance"
      owner_id:                               <computed>
      revoke_rules_on_delete:                 "false"
      vpc_id:                                 <computed>
Plan: 5 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](https://13ce0140.ngrok.io/lock?id=CMeza99%252Fterraform-up-and-running%252F.%252Fdefault).

**Comment by drts01** [comment]
atlantis apply

**Comment by drts01** [comment]
Ran Apply in dir: `.` workspace: `default`

**Apply Error**
```
exit status 1: running "sh -c terraform apply -no-color /root/.atlantis/repos/CMeza99/terraform-up-and-running/3/default/terraform-up-and-running-default.tfplan" in "/root/.atlantis/repos/CMeza99/terraform-up-and-running/3/default": 
aws_security_group.example: Creating...
  arn:                                  "" => "<computed>"
  description:                          "" => "Managed by Terraform"
  egress.#:                             "" => "<computed>"
  ingress.#:                            "" => "1"
  ingress.516175195.cidr_blocks.#:      "" => "1"
  ingress.516175195.cidr_blocks.0:      "" => "0.0.0.0/0"
  ingress.516175195.description:        "" => ""
  ingress.516175195.from_port:          "" => "8080"
  ingress.516175195.ipv6_cidr_blocks.#: "" => "0"
  ingress.516175195.protocol:           "" => "tcp"
  ingress.516175195.security_groups.#:  "" => "0"
  ingress.516175195.self:               "" => "false"
  ingress.516175195.to_port:            "" => "8080"
  name:                                 "" => "terraform-example-instance"
  owner_id:                             "" => "<computed>"
  revoke_rules_on_delete:               "" => "false"
  vpc_id:                               "" => "<computed>"
aws_security_group.elb: Creating...
  arn:                                   "" => "<computed>"
  description:                           "" => "Managed by Terraform"
  egress.#:                              "" => "1"
  egress.482069346.cidr_blocks.#:        "" => "1"
  egress.482069346.cidr_blocks.0:        "" => "0.0.0.0/0"
  egress.482069346.description:          "" => ""
  egress.482069346.from_port:            "" => "0"
  egress.482069346.ipv6_cidr_blocks.#:   "" => "0"
  egress.482069346.prefix_list_ids.#:    "" => "0"
  egress.482069346.protocol:             "" => "-1"
  egress.482069346.security_groups.#:    "" => "0"
  egress.482069346.self:                 "" => "false"
  egress.482069346.to_port:              "" => "0"
  ingress.#:                             "" => "1"
  ingress.2214680975.cidr_blocks.#:      "" => "1"
  ingress.2214680975.cidr_blocks.0:      "" => "0.0.0.0/0"
  ingress.2214680975.description:        "" => ""
  ingress.2214680975.from_port:          "" => "80"
  ingress.2214680975.ipv6_cidr_blocks.#: "" => "0"
  ingress.2214680975.protocol:           "" => "tcp"
  ingress.2214680975.security_groups.#:  "" => "0"
  ingress.2214680975.self:               "" => "false"
  ingress.2214680975.to_port:            "" => "80"
  name:                                  "" => "terraform-example-elb"
  owner_id:                              "" => "<computed>"
  revoke_rules_on_delete:                "" => "false"
  vpc_id:                                "" => "<computed>"

Error: Error applying plan:

2 error(s) occurred:

* aws_security_group.elb: 1 error(s) occurred:

* aws_security_group.elb: Error creating Security Group: InvalidGroup.Duplicate: The security group 'terraform-example-elb' already exists for VPC 'vpc-6632df0f'
	status code: 400, request id: c701a8a7-0b7a-484c-bf0d-16aaf02036ca
* aws_security_group.example: 1 error(s) occurred:

* aws_security_group.example: Error creating Security Group: InvalidGroup.Duplicate: The security group 'terraform-example-instance' already exists for VPC 'vpc-6632df0f'
	status code: 400, request id: eaefc08e-23db-4f14-ba1e-0ff0fce10f24

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



aws_security_group.example: Creating...
  arn:                                  "" => "<computed>"
  description:                          "" => "Managed by Terraform"
  egress.#:                             "" => "<computed>"
  ingress.#:                            "" => "1"
  ingress.516175195.cidr_blocks.#:      "" => "1"
  ingress.516175195.cidr_blocks.0:      "" => "0.0.0.0/0"
  ingress.516175195.description:        "" => ""
  ingress.516175195.from_port:          "" => "8080"
  ingress.516175195.ipv6_cidr_blocks.#: "" => "0"
  ingress.516175195.protocol:           "" => "tcp"
  ingress.516175195.security_groups.#:  "" => "0"
  ingress.516175195.self:               "" => "false"
  ingress.516175195.to_port:            "" => "8080"
  name:                                 "" => "terraform-example-instance"
  owner_id:                             "" => "<computed>"
  revoke_rules_on_delete:               "" => "false"
  vpc_id:                               "" => "<computed>"
aws_security_group.elb: Creating...
  arn:                                   "" => "<computed>"
  description:                           "" => "Managed by Terraform"
  egress.#:                              "" => "1"
  egress.482069346.cidr_blocks.#:        "" => "1"
  egress.482069346.cidr_blocks.0:        "" => "0.0.0.0/0"
  egress.482069346.description:          "" => ""
  egress.482069346.from_port:            "" => "0"
  egress.482069346.ipv6_cidr_blocks.#:   "" => "0"
  egress.482069346.prefix_list_ids.#:    "" => "0"
  egress.482069346.protocol:             "" => "-1"
  egress.482069346.security_groups.#:    "" => "0"
  egress.482069346.self:                 "" => "false"
  egress.482069346.to_port:              "" => "0"
  ingress.#:                             "" => "1"
  ingress.2214680975.cidr_blocks.#:      "" => "1"
  ingress.2214680975.cidr_blocks.0:      "" => "0.0.0.0/0"
  ingress.2214680975.description:        "" => ""
  ingress.2214680975.from_port:          "" => "80"
  ingress.2214680975.ipv6_cidr_blocks.#: "" => "0"
  ingress.2214680975.protocol:           "" => "tcp"
  ingress.2214680975.security_groups.#:  "" => "0"
  ingress.2214680975.self:               "" => "false"
  ingress.2214680975.to_port:            "" => "80"
  name:                                  "" => "terraform-example-elb"
  owner_id:                              "" => "<computed>"
  revoke_rules_on_delete:                "" => "false"
  vpc_id:                                "" => "<computed>"

Error: Error applying plan:

2 error(s) occurred:

* aws_security_group.elb: 1 error(s) occurred:

* aws_security_group.elb: Error creating Security Group: InvalidGroup.Duplicate: The security group 'terraform-example-elb' already exists for VPC 'vpc-6632df0f'
	status code: 400, request id: c701a8a7-0b7a-484c-bf0d-16aaf02036ca
* aws_security_group.example: 1 error(s) occurred:

* aws_security_group.example: Error creating Security Group: InvalidGroup.Duplicate: The security group 'terraform-example-instance' already exists for VPC 'vpc-6632df0f'
	status code: 400, request id: eaefc08e-23db-4f14-ba1e-0ff0fce10f24

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



```

**Comment by drts01** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
